[package]
name = "todo_app_rust_very_simple"
description = "Just for fun some Rust exercise."
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
